version: 2
jobs:
  build:
    working_directory: /usr/src/app
    docker:
      - image: mateusresende/hacker-rank:1.0.1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run app npm test
