version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run app npm test
